### PR TITLE
Add "include ActiveModel::Validations::Callbacks"

### PR DESCRIPTION
**Pull request by kbaba1001**
I want to use `before_validation` and `after_validation`.

http://api.rubyonrails.org/classes/ActiveModel/Validations/Callbacks.html

### CODE REVIEW

**Comment by cgriego** [comment]
`BasicModel` is the minimum functionality to support the ActiveModel API. I'd be interested in a pull request that adds this to `Model` with specs.

**Comment by kbaba1001** [comment]
@cgriego Thinks, reply.
I added `include ActiveModel::Validations::Callbacks` to `Model` with specs: fc7cc0f

**Comment by cgriego** [comment]
The CI job failed on Ruby 1.8.7 because of the Ruby 1.9 hash syntax in the spec. Also if you `def self.name` on the model class like is done earlier in the same file, then you shouldn't have to set and unset constants.

**Comment by kbaba1001** [comment]
@cgriego thanks, review. I fixed hash syntax, and used `self.name`

**Comment by cgriego** [comment]
This will be included in the next release. Thank you for the contribution!

**Pull request merged**
