### PR TITLE
Add support for Rails 7.2

### PR DESCRIPTION
**Pull request by eclectic-coding**
This should add Rails 7.2 support
- tests pass
- Works on my existing application with Rails 7.2/Ruby 3.3.4

### CODE REVIEW

**Comment by aramprice** [comment]
Related: https://github.com/cgriego/active_attr/issues/201

**Comment by stevenchanin** [comment]
+1 bump

**Comment by hasannadeem** [comment]
+1 bump

**Comment by emaghakyan** [comment]
+1 bump

**Comment by cgriego** [comment]
This has been released as part of v0.17. Sorry for the delay.

**Pull request closed without merging**
