### PR TITLE
Add support for Rails 7.1

### PR DESCRIPTION
**Pull request by mathieujobin**
I also removed the long list of excludes in the github action matrix, lately I found that using includes makes the list shorter and easier to maintain.

There was a failure with rails 3.0, I did not look too much and bumped the minimum version.

All tests passed including rails 7.1.1 and ruby 3.2.2

please merge and release, I will add ruby 3.3 next year

### CODE REVIEW

**Comment by rhatherall** [comment]
Will this be merged/released now Rails 7.1 has been released?

**Comment by mathieujobin** [comment]
@cgriego Hello!

**Comment by mathieujobin** [comment]
@cgriego Please merge and release this ! this is needed for https://github.com/payrollhero/webhook_system/pull/111 and others have 👍🏽  this up ...

**Comment by cgriego** [comment]
Hi everyone, sorry for the delay on this. 0.16.0 is now on Rubygems with official Rails 7.1 support.
Thank you @mathieujobin for your work and attention on this.

**Pull request closed without merging**
