### PR TITLE
object allocation: attribute_names and attributes_map

### PR DESCRIPTION
**Pull request by subvertallchris**
Two things:

`hash.keys` creates a new array each time it's called but that list doesn't change that often, so this hangs onto it.

By making `attributes_map` a little uglier, we save one more array at the beginning and then another for each pairing of attribute and value! The overall object allocation improves performance, especially when a model has a large number of properties.

### CODE REVIEW

**Comment by subvertallchris** [comment]
This may fix #134, too.

**Comment by aderyabin** [comment]
:+1:

**Comment by razum2um** [comment]
:+1:

**Comment by subvertallchris** [comment]
This should probably be modified to not change the output of `attribute!`.

**Comment by cgriego** [comment]
This will be included in the next release. Thank you for the contribution!

**Pull request merged**
